#!/usr/bin/env python3

import yaml
import ujson

# converts data file loosely from yaml [id, message] to json [word, next_words]
def main() -> None:
    processed_data: dict[str, list[str]] = {}
    with open('grunt.yml', 'r') as original_file:
        original_content: dict[str, str] = yaml.safe_load(original_file)
    for sentence in original_content.values():
        words = sentence.split()
        next_words = words[1:] + ['\0']
        for word, next_word in zip(words, next_words):
            if processed_data.get(word) is None:
                processed_data[word] = [next_word]
            else:
                processed_data[word].append(next_word)
    with open('grunt.json', 'w') as out_file:
        ujson.dump(processed_data, out_file)
    print('done!')

if __name__ == '__main__':
    main()
